
on: [push, workflow_call]

name: Build a container

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set build hash
        run: echo "build-hash=`echo $RANDOM | md5sum | head -c 20; echo;` >> $GITHUB_OUTPUT"